language: node_js
node_js:
  - "12"
before_install:
  - rm -rf yarn.lock package-lock.json node_modules/
script:
  - npm test
  - npm run build
deploy:
  provider: surge
  cleanup: true
  domain: rafael-mario-driving-school.surge.sh
  project: ./build/
