language: node_js
node_js:
  - "12.18.2"
cache:
  directories:
    - node_modules
before_script:
  - npm install --save-dev html-webpack-plugin webpack webpack-dev-server
script:
  - npm test
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: rafael-mario-driving-school.surge.sh
  project: ./build/
on:
  branch: master
